# Generated by Django 3.0 on 2020-09-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0002_noticias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticias',
            name='published_date',
        ),
        migrations.AddField(
            model_name='noticias',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
