# Generated by Django 3.0 on 2020-11-19 01:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0003_auto_20200904_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('idPublicacion', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=200)),
                ('done', models.BooleanField()),
                ('deleted', models.BooleanField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
