# Generated by Django 3.0 on 2020-11-20 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0005_auto_20201118_2231'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Noticias',
        ),
    ]
